



server:
  port: 8080


#  DISABLES THE WHITE LABEL ERROR THROWN WHEN NO MAPPING IS FOUND FOR
# A SPECIFIC URL
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service_db #change this to your database url
    password:  #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false


couponService:
  url: http://localhost:8081/api/coupons/